sonar.projectKey=softengweek4
sonar.projectName=softengweek4
sonar.projectVersion=1.0
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
sonar.exclusions=**/controller/**,**/model/SelectedLanguage.java,**/service/Language.java,**/week2/Main.java,**/week2/JavaApp.java